<Project>
    <PropertyGroup>
        <Authors>0x5bfa</Authors>
        <Company>0x5bfa</Company>
        <Version>0.1.0</Version>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/0x5bfa/WindowsTerminalControl</PackageProjectUrl>
        <RepositoryUrl>https://github.com/0x5bfa/WindowsTerminalControl.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageTags>terminal;windows-terminal;conpty;winforms;wpf;winui</PackageTags>
        <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts\packages</PackageOutputPath>
        <ContinuousIntegrationBuild Condition="'$(ContinuousIntegrationBuild)' == '' and '$(CI)' == 'true'">true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>
        <DebugType>portable</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup Condition="'$(IsPackable)' == 'true'">
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)NOTICE.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
