# Copyright (c) 0x5BFA. All rights reserved.
# Licensed under the MIT license.

name: WindowsTerminalControl CD

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  WORKING_DIR:           '${{ github.workspace }}'
  CORE_LIB_PROJ_PATH:    '${{ github.workspace }}\src\WindowsTerminalControl.Core\WindowsTerminalControl.Core.csproj'
  WINFORMS_LIB_PROJ_PATH: '${{ github.workspace }}\src\WindowsTerminalControl.WinForms\WindowsTerminalControl.WinForms.csproj'
  WPF_LIB_PROJ_PATH:     '${{ github.workspace }}\src\WindowsTerminalControl.Wpf\WindowsTerminalControl.Wpf.csproj'
  WINUI_LIB_PROJ_PATH:   '${{ github.workspace }}\src\WindowsTerminalControl.WinUI\WindowsTerminalControl.WinUI.csproj'
  OUTPUT_DIR:            '${{ github.workspace }}\artifacts\packages'

jobs:
  build-pack-publish:
    runs-on: windows-2025-vs2026
    environment: release
    env:
      CONFIGURATION: Release
      PLATFORM: x64

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Pack Core
        run: msbuild /restore $env:CORE_LIB_PROJ_PATH /t:Pack /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:ContinuousIntegrationBuild=true /p:PackageOutputPath=$env:OUTPUT_DIR

      - name: Pack WinForms
        run: msbuild /restore $env:WINFORMS_LIB_PROJ_PATH /t:Pack /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:ContinuousIntegrationBuild=true /p:PackageOutputPath=$env:OUTPUT_DIR

      - name: Pack WPF
        run: msbuild /restore $env:WPF_LIB_PROJ_PATH /t:Pack /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:ContinuousIntegrationBuild=true /p:PackageOutputPath=$env:OUTPUT_DIR

      - name: Pack WinUI
        run: msbuild /restore $env:WINUI_LIB_PROJ_PATH /t:Pack /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:ContinuousIntegrationBuild=true /p:PackageOutputPath=$env:OUTPUT_DIR

      - name: Upload nupkg artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuPkg artifacts
          path: |
            ${{ env.OUTPUT_DIR }}\*.nupkg
            ${{ env.OUTPUT_DIR }}\*.snupkg
          if-no-files-found: error

      - name: Login to NuGet.org with trusted publishing
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: ${{ vars.NUGET_USER || '0x5bfa' }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push ${{ env.OUTPUT_DIR }}\*.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push ${{ env.OUTPUT_DIR }}\*.snupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
